-- MySQL Script generated by MySQL Workbench
-- Fri Jul 23 13:37:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eltecico_tecnologico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eltecico_tecnologico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eltecico_tecnologico` DEFAULT CHARACTER SET utf8 ;
USE `eltecico_tecnologico` ;

-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`estudiante` (
  `idestudiante` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(25) NULL,
  `nombre_apellido` VARCHAR(250) NULL,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(100) NULL,
  `celular` VARCHAR(20) NULL,
  `correo` VARCHAR(200) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idestudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NULL,
  `detalle` VARCHAR(500) NULL,
  `nivel` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`docente` (
  `iddocente` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(25) NULL,
  `nombre_apellido` VARCHAR(250) NULL,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `edad` VARCHAR(10) NULL,
  `celular` VARCHAR(20) NULL,
  `correo` VARCHAR(150) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`iddocente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`ciclo_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`ciclo_curso` (
  `idciclo_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  `detalle` VARCHAR(500) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `cant_horas` VARCHAR(45) NULL,
  `f_emision_certificado_b` VARCHAR(45) NULL,
  `estado` INT NULL DEFAULT 1,
  `curso_idcurso` INT NOT NULL,
  `docente_iddocente` INT NOT NULL,
  PRIMARY KEY (`idciclo_curso`),
  INDEX `fk_ciclo_curso_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_ciclo_curso_docente1_idx` (`docente_iddocente` ASC),
  CONSTRAINT `fk_ciclo_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `eltecico_tecnologico`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ciclo_curso_docente1`
    FOREIGN KEY (`docente_iddocente`)
    REFERENCES `eltecico_tecnologico`.`docente` (`iddocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`matricula` (
  `idmatricula` INT NOT NULL AUTO_INCREMENT,
  `registro_nombre` VARCHAR(45) NULL,
  `registro_num` INT NULL,
  `nota` VARCHAR(10) NULL,
  `f_emision_certificado_e` VARCHAR(40) NULL COMMENT 'Fecah de emisión de certificado Estudiante. La última vez que el estudiante solicitó su certificado.\n',
  `estado` INT NULL,
  `ciclo` VARCHAR(45) NULL,
  `estudiante_idestudiante` INT NOT NULL,
  `ciclo_curso_idciclo_curso` INT NOT NULL,
  INDEX `fk_matricula_estudiante_idx` (`estudiante_idestudiante` ASC),
  PRIMARY KEY (`idmatricula`),
  INDEX `fk_matricula_ciclo_curso1_idx` (`ciclo_curso_idciclo_curso` ASC),
  CONSTRAINT `fk_matricula_estudiante`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `eltecico_tecnologico`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_ciclo_curso1`
    FOREIGN KEY (`ciclo_curso_idciclo_curso`)
    REFERENCES `eltecico_tecnologico`.`ciclo_curso` (`idciclo_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`institucion` (
  `idinstitucion` INT NOT NULL,
  `nombre` VARCHAR(300) NULL,
  `detalle` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idinstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`sede` (
  `idsede` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `detalle` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idsede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`certificados_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`certificados_temp` (
  `idcertificados_temp` INT NOT NULL AUTO_INCREMENT,
  `registro` VARCHAR(45) NULL,
  `nombre_apellido` VARCHAR(250) NULL,
  `dni` VARCHAR(25) NULL,
  `celular` VARCHAR(20) NULL,
  `nota` VARCHAR(10) NULL,
  `curso` VARCHAR(500) NULL,
  `nivel` VARCHAR(50) NULL,
  `horas` VARCHAR(40) NULL,
  `fecha_inicio` VARCHAR(70) NULL,
  `fecha_fin` VARCHAR(70) NULL,
  `fecha_emision` VARCHAR(70) NULL,
  PRIMARY KEY (`idcertificados_temp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`recurso` (
  `idrecurso_clase` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `link_clase` VARCHAR(200) NULL,
  `link_archivos` VARCHAR(200) NULL,
  `apuntes` TEXT NULL,
  `observaciones` VARCHAR(250) NULL,
  `estado` INT NULL,
  `ciclo_curso_idciclo_curso` INT NOT NULL,
  PRIMARY KEY (`idrecurso_clase`),
  INDEX `fk_recurso_ciclo_curso1_idx` (`ciclo_curso_idciclo_curso` ASC),
  CONSTRAINT `fk_recurso_ciclo_curso1`
    FOREIGN KEY (`ciclo_curso_idciclo_curso`)
    REFERENCES `eltecico_tecnologico`.`ciclo_curso` (`idciclo_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltecico_tecnologico`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eltecico_tecnologico`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(500) NULL,
  `dni` VARCHAR(25) NULL DEFAULT '12345678',
  `tipo_usuario` INT NULL DEFAULT 1,
  `nombre` VARCHAR(50) NULL DEFAULT 'itec',
  `apellidos` VARCHAR(75) NULL DEFAULT 'sin apellido',
  `telefono` VARCHAR(45) NULL DEFAULT '987654321',
  `ruta_foto` VARCHAR(200) NULL,
  `estado` INT NULL DEFAULT 0,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
